[buildPlans.Romeosevka]
family = "Romeosevka"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

[buildPlans.Romeosevka.variants.design]
one = "base-flat-top-serif"
two = "curly-neck-serifed"
three = "flat-top-serifed"
five = "upright-arched-serifed"
six = "open-contour"
seven = "bend-serifed"
eight = "two-circles"
nine = "open-contour"
zero = "oval-tall-slashed"
capital-d = "more-rounded-serifless"
capital-g = "toothed-serifless-hooked"
capital-j = "serifed-symmetric"
capital-k = "symmetric-touching-serifless"
capital-r = "standing-serifless"
f = "flat-hook-extended-crossbar-at-x-height"
i = "serifed-flat-tailed"
k = "symmetric-touching-serifless"
l = "serifed-flat-tailed"
t = "flat-hook"
w = "straight-flat-top-serifless"
long-s = "bent-hook-descending"
eszet = "longs-s-lig-descending-serifless"
lower-eth = "straight-bar"
lower-gamma = "straight"
lower-delta = "flat-top"
lower-iota = "tailed-serifed"
lower-kappa = "symmetric-touching-serifless"
lower-mu = "toothed-serifless"
lower-nu = "straight"
lower-tau = "tailed"
lower-upsilon = "straight-serifless"
partial-derivative = "straight-bar"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-em = "hanging-serifless"
cyrl-capital-ya = "standing-serifless"
cyrl-ya = "standing-serifless"
tilde = "low"
asterisk = "hex-low"
underscore = "low"
caret = "high"
paren = "large-contour"
brace = "curly-flat-boundary"
number-sign = "slanted-tall"
percent = "rings-continuous-slash"
bar = "force-upright"
pilcrow = "low"
micro-sign = "toothed-bottom-right-serifed"
decorative-angle-brackets = "tall"

[buildPlans.Romeosevka.variants.italic]
one = "base-flat-top-serif"
two = "curly-neck-serifed"
three = "flat-top-serifed"
five = "upright-arched-serifed"
six = "open-contour"
seven = "bend-serifed"
eight = "two-circles"
nine = "open-contour"
zero = "oval-tall-slashed"
capital-j = "serifed-symmetric"
capital-k = "symmetric-touching-serifless"
capital-r = "standing-serifless"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner-serifless"
f = "flat-hook-tailed-crossbar-at-x-height"
g = "single-storey-earless-corner"
h = "tailed-serifless"
i = "tailed-serifed"
k = "cursive-serifless"
l = "tailed-serifed"
m = "tailed-serifless"
n = "tailed-serifless"
q = "earless-corner-diagonal-tailed-serifless"
t = "bent-hook"
v = "curly-serifless"
w = "curly-flat-top-serifless"
x = "semi-chancery-straight-serifless"
z = "curly-serifless"
long-s = "bent-hook-descending"
eszet = "longs-s-lig-descending-serifless"
lower-eth = "curly-bar"
lower-gamma = "casual"
lower-delta = "rounded"
lower-iota = "tailed-serifed"
lower-kappa = "symmetric-touching-serifless"
lower-lambda = "straight-turn"
lower-mu = "toothed-serifless"
lower-nu = "straight"
lower-tau = "tailed"
lower-upsilon = "straight-serifless"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-el = "tailed"
cyrl-em = "hanging-serifless"
cyrl-capital-u = "cursive-serifless"
cyrl-yeri = "cursive"
cyrl-yery = "cursive-tailed"
cyrl-capital-ya = "standing-serifless"
cyrl-ya = "standing-serifless"
tilde = "low"
asterisk = "hex-low"
underscore = "low"
caret = "high"
paren = "large-contour"
brace = "curly-flat-boundary"
number-sign = "slanted-tall"
percent = "rings-continuous-slash"
bar = "force-upright"
pilcrow = "low"
micro-sign = "toothed-bottom-right-serifed"
decorative-angle-brackets = "tall"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

  [buildPlans.Romeosevka.ligations]
  inherits = "dlig"

[buildPlans.Romeosevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Romeosevka.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.Romeosevka.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.Romeosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Romeosevka.slopes.Italic]
angle = 15
shape = "italic"
menu = "italic"
css = "italic"
# ------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------

[buildPlans.RomeosevkaProp]
family = "RomeosevkaProp"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.RomeosevkaProp.variants.design]
one = "base-flat-top-serif"
two = "curly-neck-serifed"
three = "flat-top-serifed"
five = "oblique-flat-serifed"
six = "open-contour"
seven = "bend-serifed"
eight = "two-circles"
nine = "open-contour"
zero = "oval-tall-slashed"
capital-d = "more-rounded-serifless"
capital-i = "short-serifed"
capital-j = "descending-serifed-symmetric"
capital-k = "symmetric-touching-serifless"
capital-m = "flat-bottom-serifless"
capital-r = "standing-serifless"
capital-w = "straight-flat-top-serifless"
f = "flat-hook-extended"
i = "flat-tailed"
k = "symmetric-touching-serifless"
l = "semi-tailed"
r = "compact-serifless"
t = "flat-hook"
w = "straight-flat-top-serifless"
long-s = "bent-hook-descending"
eszet = "sulzbacher-descending-serifless"
lower-eth = "curly-bar"
lower-gamma = "straight"
lower-iota = "flat-tailed"
lower-lambda = "straight-turn"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ka = "symmetric-connected-serifless"
cyrl-ka = "symmetric-connected-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
cyrl-ef = "split-serifless"
cyrl-capital-ya = "standing-serifless"
cyrl-ya = "standing-serifless"
ellipsis-density = "dense"
asterisk = "hex-mid"
caret = "high"
paren = "large-contour"
brace = "curly-flat-boundary"
number-sign = "slanted-tall"
at = "fourfold"
percent = "rings-continuous-slash"
pilcrow = "low"

[buildPlans.RomeosevkaProp.variants.italic]
capital-k = "curly-serifless"
capital-q = "closed-swash"
capital-u = "tailed-serifless"
capital-v = "curly-serifless"
capital-w = "curly-flat-top-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "single-storey-flat-top-tailed"
b = "flat-bottom-serifless"
d = "flat-bottom-serifless"
f = "flat-hook-tailed-crossbar-at-x-height"
g = "single-storey-flat-top-serifless"
h = "tailed-serifless"
i = "tailed"
k = "diagonal-tailed-cursive-serifless"
l = "tailed"
m = "tailed-serifless"
n = "tailed-serifless"
q = "flat-top-diagonal-tailed-serifless"
r = "flat-top-serifless"
t = "bent-hook"
v = "curly-serifless"
w = "curly-flat-top-serifless"
x = "semi-chancery-straight-serifless"
z = "curly-serifless"
long-s = "bent-hook-tailed"
eszet = "sulzbacher-tailed-serifless"
lower-beta = "cursive"
lower-gamma = "casual"
lower-eta = "flat-top-serifless"
lower-theta = "cursive"
lower-iota = "tailed"
lower-kappa = "curly-serifless"
lower-lambda = "curly-tailed-turn"
lower-pi = "diagonal-tailed"
lower-chi = "chancery"
partial-derivative = "closed-contour"
cyrl-ve = "cursive-tall"
cyrl-capital-zhe = "cursive"
cyrl-zhe = "cursive"
cyrl-ze = "tall-serifless"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-el = "tailed"
cyrl-en = "tailed-serifless"
cyrl-ef = "cursive"
cyrl-che = "tailed"
cyrl-yeri = "cursive"
cyrl-yery = "cursive-tailed"

[buildPlans.RomeosevkaProp.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.RomeosevkaProp.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.RomeosevkaProp.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.RomeosevkaProp.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.RomeosevkaProp.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
# ------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------

[buildPlans.RomeosevkaSlab]
family = "RomeosevkaSlab"
spacing = "fontconfig-mono"
serifs = "slab"
noCvSs = false
exportGlyphNames = false

[buildPlans.RomeosevkaSlab.variants.design]
eight = "two-circles"
zero = "oval-tall-slashed"
capital-q = "closed-swash"
f = "extended"
asterisk = "hex-low"
underscore = "low"
caret = "high"
paren = "large-contour"
brace = "curly-flat-boundary"
number-sign = "upright-tall"
at = "fourfold"
percent = "rings-continuous-slash"
bar = "force-upright"
pilcrow = "low"
decorative-angle-brackets = "tall"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"

  [buildPlans.RomeosevkaSlab.ligations]
  inherits = "dlig"

[buildPlans.RomeosevkaSlab.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.RomeosevkaSlab.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.RomeosevkaSlab.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.RomeosevkaSlab.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.RomeosevkaSlab.slopes.Italic]
angle = 15
shape = "italic"
menu = "italic"
css = "italic"

# ------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------
