[buildPlans.Romeosevka]
family = "Romeosevka"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Romeosevka.variants.design]
one = "base-flat-top-serif"
two = "straight-neck-serifless"
five = "oblique-flat-serifless"
six = "open-contour"
seven = "straight-serifed"
eight = "two-circles"
nine = "open-contour"
zero = "oval-tall-slashed"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
capital-m = "flat-bottom-serifless"
capital-n = "standard-serifless"
capital-q = "closed-swash"
capital-r = "standing-serifless"
capital-w = "straight-flat-top-serifless"
a = "double-storey-serifless"
f = "flat-hook-extended"
g = "single-storey-serifless"
i = "flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "flat-tailed"
q = "tailed-serifless"
r = "serifless"
t = "flat-hook"
w = "straight-flat-top-serifless"
x = "straight-serifless"
y = "straight-turn-serifless"
z = "straight-serifless"
capital-eszet = "flat-top-serifless"
long-s = "bent-hook-descending"
eszet = "longs-s-lig-descending-serifless"
capital-thorn = "asymmetric-serifless"
lower-gamma = "straight"
lower-delta = "flat-top"
lower-theta = "oval"
lower-iota = "tailed-serifed"
lower-kappa = "symmetric-touching-serifless"
lower-lambda = "straight-turn"
lower-mu = "toothed-serifless"
lower-nu = "straight"
lower-xi = "flat-top"
lower-tau = "tailed"
lower-upsilon = "straight-serifless"
lower-chi = "straight-serifless"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ka = "symmetric-touching-serifless"
cyrl-ka = "symmetric-touching-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
cyrl-ef = "serifless"
cyrl-capital-ya = "standing-serifless"
cyrl-ya = "standing-serifless"
asterisk = "hex-low"
caret = "high"
paren = "large-contour"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "upright-tall"
at = "fourfold"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
pilcrow = "low"
decorative-angle-brackets = "tall"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"

[buildPlans.Romeosevka.variants.italic]
capital-k = "curly-serifless"
a = "single-storey-serifed"
b = "toothless-corner-serifless"
f = "flat-hook-tailed"
g = "single-storey-earless-corner"
h = "tailed-serifless"
i = "tailed"
j = "serifed"
k = "cursive-serifless"
l = "tailed"
m = "tailed-serifless"
n = "tailed-serifless"
p = "earless-corner-serifless"
q = "diagonal-tailed-serifless"
t = "bent-hook"
v = "straight-serifless"
w = "straight-flat-top-serifless"
x = "semi-chancery-straight-serifless"
y = "cursive-flat-hook-serifless"
z = "curly-serifless"
capital-eszet = "flat-top-serifless"
long-s = "bent-hook-descending"
eszet = "longs-s-lig-descending-serifless"
capital-thorn = "asymmetric-serifless"
lower-gamma = "casual"
lower-delta = "rounded"
lower-theta = "cursive"
lower-iota = "tailed-serifed"
lower-kappa = "curly-serifless"
lower-lambda = "curly-tailed-turn"
lower-mu = "toothed-serifless"
lower-nu = "curly"
lower-xi = "rounded"
lower-tau = "tailed"
lower-upsilon = "casual-serifless"
lower-chi = "semi-chancery-curly-serifless"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-el = "tailed"
cyrl-en = "tailed-serifless"
cyrl-er = "earless-corner-serifless"
cyrl-ef = "serifless"
cyrl-che = "tailed"
cyrl-yeri = "cursive"
cyrl-yery = "round-tailed"
cyrl-capital-ya = "standing-serifless"
cyrl-ya = "standing-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
paren = "large-contour"
brace = "curly-flat-boundary"
guillemet = "curly"
number-sign = "upright-tall"
at = "fourfold"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
pilcrow = "low"
decorative-angle-brackets = "tall"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"

  [buildPlans.Romeosevka.ligations]
  inherits = "dlig"

[buildPlans.Romeosevka.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Romeosevka.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.Romeosevka.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Romeosevka.slopes.Italic]
angle = 15
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.RomeosevkaQp]
family = "RomeosevkaQP"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.RomeosevkaQp.variants.design]
one = "base-flat-top-serif"
two = "straight-neck-serifless"
five = "oblique-flat-serifless"
six = "open-contour"
seven = "straight-serifed"
eight = "two-circles"
nine = "open-contour"
zero = "oval-tall-slashed"
capital-d = "more-rounded-serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
capital-m = "flat-bottom-serifless"
capital-n = "standard-serifless"
capital-q = "closed-swash"
capital-r = "standing-serifless"
capital-w = "straight-flat-top-serifless"
a = "double-storey-serifless"
f = "flat-hook-extended"
g = "single-storey-serifless"
i = "flat-tailed"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "flat-tailed"
q = "tailed-serifless"
r = "serifless"
t = "flat-hook"
w = "straight-flat-top-serifless"
x = "straight-serifless"
y = "straight-turn-serifless"
z = "straight-serifless"
capital-eszet = "flat-top-serifless"
long-s = "bent-hook-descending"
eszet = "longs-s-lig-descending-serifless"
capital-thorn = "asymmetric-serifless"
lower-gamma = "straight"
lower-delta = "flat-top"
lower-theta = "oval"
lower-iota = "tailed-serifed"
lower-kappa = "symmetric-touching-serifless"
lower-lambda = "straight-turn"
lower-mu = "toothed-serifless"
lower-nu = "straight"
lower-xi = "flat-top"
lower-tau = "tailed"
lower-upsilon = "straight-serifless"
lower-chi = "straight-serifless"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ka = "symmetric-touching-serifless"
cyrl-ka = "symmetric-touching-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
cyrl-ef = "serifless"
cyrl-capital-ya = "standing-serifless"
cyrl-ya = "standing-serifless"
asterisk = "hex-low"
caret = "high"
paren = "large-contour"
brace = "curly-flat-boundary"
guillemet = "straight"
number-sign = "upright-tall"
at = "fourfold"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
pilcrow = "low"
decorative-angle-brackets = "tall"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"

[buildPlans.RomeosevkaQp.variants.italic]
capital-k = "curly-serifless"
a = "single-storey-serifed"
b = "toothless-corner-serifless"
f = "flat-hook-tailed"
g = "single-storey-earless-corner"
h = "tailed-serifless"
i = "tailed"
j = "serifed"
k = "cursive-serifless"
l = "tailed"
m = "tailed-serifless"
n = "tailed-serifless"
p = "earless-corner-serifless"
q = "diagonal-tailed-serifless"
t = "bent-hook"
v = "straight-serifless"
w = "straight-flat-top-serifless"
x = "semi-chancery-straight-serifless"
y = "cursive-flat-hook-serifless"
z = "curly-serifless"
capital-eszet = "flat-top-serifless"
long-s = "bent-hook-descending"
eszet = "longs-s-lig-descending-serifless"
capital-thorn = "asymmetric-serifless"
lower-gamma = "casual"
lower-delta = "rounded"
lower-theta = "cursive"
lower-iota = "tailed-serifed"
lower-kappa = "curly-serifless"
lower-lambda = "curly-tailed-turn"
lower-mu = "toothed-serifless"
lower-nu = "curly"
lower-xi = "rounded"
lower-tau = "tailed"
lower-upsilon = "casual-serifless"
lower-chi = "semi-chancery-curly-serifless"
cyrl-capital-zhe = "symmetric-touching"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-el = "tailed"
cyrl-en = "tailed-serifless"
cyrl-er = "earless-corner-serifless"
cyrl-ef = "serifless"
cyrl-che = "tailed"
cyrl-yeri = "cursive"
cyrl-yery = "round-tailed"
cyrl-capital-ya = "standing-serifless"
cyrl-ya = "standing-serifless"
asterisk = "hex-low"
underscore = "above-baseline"
paren = "large-contour"
brace = "curly-flat-boundary"
guillemet = "curly"
number-sign = "upright-tall"
at = "fourfold"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
pilcrow = "low"
decorative-angle-brackets = "tall"
lig-neq = "slightly-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"

  [buildPlans.RomeosevkaQp.ligations]
  inherits = "dlig"

[buildPlans.RomeosevkaQp.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.RomeosevkaQp.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.RomeosevkaQp.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.RomeosevkaQp.slopes.Italic]
angle = 15
shape = "italic"
menu = "italic"
css = "italic"
